language: php
dist: trusty
sudo: false

matrix:
  include:
    - php: 7.1
      env: LARAVEL_VERSION=5.5.*
    - php: 7.2
      env: LARAVEL_VERSION=5.5.*

install:
  - travis_retry composer install --no-suggest --prefer-dist -n -o

script:
  - if [ "$TRAVIS_PHP_VERSION" != "7.0" ]; then vendor/bin/phpunit; fi